[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npx prisma migrate resolve --rolled-back 20251028000000_init || true', 'npx prisma db push --accept-data-loss', 'npm run build']

[start]
cmd = 'npm start'